---
title: "Sensitivity Analysis"
format: html
editor: visual
---

```{r}
# Example: 5-year cash flow forecast (in millions)
cf <- c(-1534.2,-1104.4,-870.1,-457.0,145.9)  # Free cash flows
r <- 0.1237                       # Discount rate
terminal_growth <- 0.04           # Perpetual growth rate

# Terminal Value
terminal_value <- cf[5] * (1 + terminal_growth) / (r - terminal_growth) # steady growth the company will maintain once it reaches maturity

# Present Value of Cash Flows
pv_cf <- sum(cf / (1 + r)^(1:5)) + terminal_value / (1 + r)^5

pv_cf



```

```{r}
discount_rates <- seq(0.10, 0.14, by = 0.01) # (.11, .12, ... , .14)
growth_rates <- seq(0.01, 0.05, by = 0.01) # (.01, .02, ... , .05)
# => total 35 scenarios

sensitivity <- expand.grid(r = discount_rates, g = growth_rates) # Makes grid of the 35 scenarios
sensitivity$Value <- mapply(function(r, g) {
  terminal_value <- cf[5] * (1 + g) / (r - g)
  sum(cf / (1 + r)^(1:5)) + terminal_value / (1 + r)^5
}, sensitivity$r, sensitivity$g)

head(sensitivity)

```

```{r}
library(ggplot2)

ggplot(sensitivity, aes(x = r, y = g, fill = Value)) +
  geom_tile() +
  scale_fill_gradient(low = "lightblue", high = "darkgreen") +
  labs(
    title = "DCF Sensitivity Analysis",
    x = "Discount Rate",
    y = "Terminal Growth Rate",
    fill = "Firm Value ($M)"
  ) +
  theme_minimal()
# dark green = higher valuations (undervalued), light blue = lower valuations (overvalued)
```

```{r}
market_cap <- 1000 # market cap of company 
undervaluation <- ((pv_cf - market_cap) / market_cap)*100
undervaluation
# positive = undervalued, negative = overvalued
```

```{r}
barplot(c(market_cap, pv_cf), names.arg = c("Market Cap", "DCF Value"),
        col = c("lightblue", "darkgreen"),
        main = "Market vs. Intrinsic Value")
# Shows intrinsic value of company is 304% lower than current market cap. indicates potential downside, suggesting overvalued at current price

```
